import React from 'react'
import Head from 'next/head'
import s from "../favourite/favourite.module.scss"

const favourite = () => {
  return (
    <>
      <Head>
        <title>Main</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        
      </main>
    </>
  )
}

export default favourite
