import React from 'react'
import Head from 'next/head'
import s from "../favourite/favourite.module.scss"
// components
import Filter from '@/components/filter'
import Card from "@/components/card"
// link
import Link from 'next/link'
// images
import Image from 'next/image'
// product list
import Products_json from "@/modules/server/products/products_all.json"
// redux
import { useSelector } from "react-redux";


const favourite = () => {
  const favList = useSelector((state: any) => state.favourite.fav_list);
  return (
    <>
      <Head>
        <title>Favourite</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={s.main}>
        <Filter></Filter>
        {/* <section className={s.filter}>
          <input type="text" />
        </section> */}
        <section className={s.list}>
          <div className={s.list__top}>
            <h1>Favourite</h1>
            <Link href={"/product"}>View all</Link>
          </div>
          {
            favList.length > 0 ? <div className={s.list__items}>{Products_json.map((product:any)=>{
              if(favList.indexOf(product.id)>=0){
                return(
                  <Card key={product.id} product_data={product}></Card>
                )
              }
            })}</div> : <div className={s.list__error}>No favourite yet.</div>
          }
          <div className={s.list__bottom}>
            <h2>{favList.length ? `${favList.length} Cars` : `Zero`}</h2>
          </div>
        </section>
      </main>
    </>
  )
}

export default favourite
