import React from 'react'
import Head from 'next/head'
import s from "../favourite/favourite.module.scss"
// components
import Filter from '@/components/filter'
import Card from "@/components/card"
// link
import Link from 'next/link'
// images
import Image from 'next/image'
// product list
import Products_json from "@/modules/server/products/products.json"
// redux
import redux from "@/redux/features/favourite"

const favourite = () => {
  if (typeof window !== 'undefined') {

    let list = [localStorage.getItem("Test")]
    list.map((id : any)=>{
      console.log(id)
    })
  }
  return (
    <>
      <Head>
        <title>Favourite</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        
      </main>
    </>
  )
}

export default favourite
