import React, { useEffect, useState, useMemo } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import s from "../product/single.module.scss";
import data from "@/modules/server/products/products.json";
// components
import Card_mini from "@/components/card_mini";
// link
import Link from "next/link";
// images
import Image from "next/image";
import Location from "@/assets/img/Location.png";
import Heart from "@/assets/img/heart_card.svg";
// redux
import { useSelector, useDispatch } from "react-redux";
import { changeFavoriteList } from "@/redux/features/favourite";
// product list
import Products_json from "@/modules/server/products/products_all.json";
// swiper
import { Navigation, Pagination, Scrollbar, A11y } from "swiper/modules";

import { Swiper, SwiperSlide } from "swiper/react";

// Import Swiper styles
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/scrollbar";
import filter from "@/components/filter";
// interface
import { CardItem } from "@/interfaces";

const singleProduct = () => {
  const router = useRouter();
  const [car, setCar] = useState<any>(null);
  // on change router
  useEffect(() => {
    const ID = router.query.id;
    if (ID) {
      const CAR_DATA = data.filter((el: { id: number | string }) => {
        if (el.id == ID) {
          return el;
        }
      });
      setCar(CAR_DATA[0]);
    }
  }, [router.query.id]);

  const sliderSettings = {
    slidesPerView: 1,
    navigation: true,
    loop: true,
    spaceBetween: 6,
    parallax: true,
    allowTouchMove: true,
  };

  const dispatch = useDispatch();
  const favList = useSelector((state: any) => state.favourite.fav_list);

  const isFav = useMemo(() => {
    if (favList.indexOf(router.query.id) >= 0) {
      return true;
    } else {
      return false;
    }
  }, [favList]);

  return (
    <>
      <Head>
        <title>{car?.name}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className={s.product}>
          <Swiper className={s.product__slider} {...sliderSettings}>
            {car?.photos.map(( photo : string )=>{
              return (
              <SwiperSlide>
                <Image src={photo} alt="product-photo"
                  width={10}
                  height={10}
                  unoptimized></Image>
              </SwiperSlide>)
            })}
          </Swiper>
          <div className={s.product__line}></div>
          <div className={s.product__info}>
            <h1>{car?.name}</h1>
            <div className={s.product__info_location}>
              <Image src={Location} alt="location-icon"></Image>
              <p>{car?.location}</p>
            </div>
            <h2>{car?.run ? `Run: ${car?.run}` : 'No run.'}</h2>
            <span>{car?.price} $</span>
            <Link href={`/cta`}>Msg owner</Link>
            <Image
              onClick={() => dispatch(changeFavoriteList(Number(router.query.id)))}
              src={Heart}
              alt="heart-icon"
              className={`${s.product__info_fav} ${isFav ? "active" : ""}`}
            ></Image>
          </div>
        </section>
        <section className={s.list}>
          <div className={s.list__top}>
            <h1>Similar</h1>
            <Link href={"/"}>View all</Link>
          </div>
          {Products_json.length > 0 ? (
            <div className={s.list__items}>
              {Products_json.map((product: any) => {
                return (
                  <Card_mini
                    key={product.id}
                    product_data={product}
                  ></Card_mini>
                );
              })}
            </div>
          ) : (
            <div className={s.list__error}>No products yet.</div>
          )}
        </section>
      </main>
    </>
  );
};

export default singleProduct;
