import React, { useEffect, useState } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import s from "../product/single.module.scss";
import data from "@/modules/server/products/products.json";
// components
import Card_mini from "@/components/card_mini";
// link
import Link from "next/link";
// images
import Image from "next/image";
import Location from "@/assets/img/Location.png";
import Test from "@/assets/img(products)/land-rover_range-rover-evoque__525771031f(1).png";
import Heart from "@/assets/img/heart_card.svg";
// product list
import Products_json from "@/modules/server/products/products.json";
// swiper
import { Navigation, Pagination, Scrollbar, A11y } from "swiper/modules";

import { Swiper, SwiperSlide } from "swiper/react";

// Import Swiper styles
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/scrollbar";
import filter from "@/components/filter";
import { CardItem } from "@/interfaces";

const singleProduct = () => {
  const router = useRouter();
  const [car, setCar] = useState<any>(null);
  // on change router
  useEffect(() => {
    const ID = router.query.id;
    if (ID) {
      const CAR_DATA = data.filter((el: { id: number | string }) => {
        if (el.id == ID) {
          return el;
        }
      });
      setCar(CAR_DATA[0]);
    }
  }, [router.query.id]);

  const sliderSettings = {
    slidesPerView: 1,
    navigation: true,
    loop: true,
    spaceBetween: 6,
    parallax: true,
    allowTouchMove: true,
  };

  return (
    <>
      <Head>
        <title>Product Name</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className={s.product}>
          <Swiper className={s.product__slider} {...sliderSettings}>
            <SwiperSlide>
              <Image src={Test} alt="product-photo"></Image>
            </SwiperSlide>
            <SwiperSlide>
              <Image src={Test} alt="product-photo"></Image>
            </SwiperSlide>
            <SwiperSlide>
              <Image src={Test} alt="product-photo"></Image>
            </SwiperSlide>
          </Swiper>
          <div className={s.product__line}></div>
          <div className={s.product__info}>
            <h1>{car?.name}</h1>
            <div className={s.product__info_location}>
              <Image src={Location} alt="location-icon"></Image>
              <p>{car?.location}</p>
            </div>
            <h2>Run: {car?.run}</h2>
            <span>XXXXX $</span>
            <Link href={`/cta`}>Msg owner</Link>
            <Image
              className={s.product__info_fav}
              src={Heart}
              alt="heart-icon"
            ></Image>
          </div>
        </section>
        <section className={s.list}>
          <div className={s.list__top}>
            <h1>Similar</h1>
            <Link href={"/"}>View all</Link>
          </div>
          {Products_json.length > 0 ? (
            <div className={s.list__items}>
              {Products_json.map((product: any) => {
                return (
                  <Card_mini
                    key={product.id}
                    product_data={product}
                  ></Card_mini>
                );
              })}
            </div>
          ) : (
            <div className={s.list__error}>No products yet.</div>
          )}
        </section>
      </main>
    </>
  );
};

export default singleProduct;
