import React from 'react'
import { useRouter } from 'next/router'
import Head from 'next/head'
import s from "../product/single.module.scss"
// components
import Card_mini from "@/components/card_mini"
// link
import Link from 'next/link'
// images
import Image from 'next/image'
import Location from "@/assets/img/Location.png"
import Test from "@/assets/img(products)/land-rover_range-rover-evoque__525771031f(1).png"
import Heart from "@/assets/img/heart_card.svg"
// product list
import Products_json from "@/modules/server/products/products.json"
// swiper
import { Navigation, Pagination, Scrollbar, A11y } from 'swiper/modules';

import { Swiper, SwiperSlide } from 'swiper/react';

// Import Swiper styles
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import 'swiper/css/scrollbar';


const singleProduct = () => {
  const router = useRouter()
  console.log(router.query)
  const sliderSettings = {
      slidesPerView: 1,
      navigation: true,
      loop: true,
      spaceBetween: 6,
      parallax: true,
      allowTouchMove: true,
      
  }

  return (
    <>
      <Head>
        <title>Product Name</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className={s.product}>
          <Swiper className={s.product__slider} {...sliderSettings}>
            <SwiperSlide><Image src={Test} alt="product-photo"></Image></SwiperSlide>
            <SwiperSlide><Image src={Test} alt="product-photo"></Image></SwiperSlide>
            <SwiperSlide><Image src={Test} alt="product-photo"></Image></SwiperSlide>
          </Swiper>
          <div className={s.product__line}></div>
          <div className={s.product__info}>
            <h1>Name</h1>
            <div className={s.product__info_location}>
              <Image src={Location} alt='location-icon'></Image>
              <p>Location</p>
            </div>
            <h2>
              Run
            </h2>
            <span>XXXXX $</span>
            <Link href={`/cta`}>Msg owner</Link>
            <Image className={s.product__info_fav} src={Heart} alt="heart-icon"></Image>
          </div>
        </section>
        <section className={s.list}>
          <div className={s.list__top}>
            <h1>Similar</h1>
            <Link href={"/"}>View all</Link>
          </div>
          {
            Products_json.length > 0 ? <div className={s.list__items}>{Products_json.map((product:any)=>{
              return(
                <Card_mini key={product.id} product_data={product}></Card_mini>
              )
            })}</div> : <div className={s.list__error}>No products yet.</div>
          }
        </section>
      </main>
    </>
  )
}

export default singleProduct
