import React from 'react'
import { useRouter } from 'next/router'
import Head from 'next/head'
import s from "../product/single.module.scss"
// link
import Link from 'next/link'
// images
import Image from 'next/image'

const singleProduct = () => {
  const router = useRouter()
  console.log(router)
  return (
    <>
      <Head>
        <title>Main</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        d
      </main>
    </>
  )
}

export default singleProduct
