import React from 'react'
import Head from 'next/head'
import styles from '@/styles/Home.module.scss'
// link
import Link from 'next/link'
// images
import Image from 'next/image'


export default function Home() {
  return (
    <>
      <Head>
        <title>Main</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        
      </main>
    </>
  )
}
