import React, { useEffect, useState } from 'react'
import { useRouter } from 'next/router'
import Head from 'next/head'
import s from "../cta/cta.module.scss"
// link
import Link from "next/link";
// images
import Image from "next/image";
// product list
import Products_json_all from "@/modules/server/products/products_all.json";
import Inst from "@/assets/img/insta-logo.png"
import Tg from "@/assets/img/tg-logo.png"
import Fb from "@/assets/img/fb-logo.png"

// interface
import { CardItem } from "@/interfaces";


const cta = () => {
  const router = useRouter();
  const [car, setCar] = useState<any>(null);
  // on change router
  useEffect(() => {
    const ID = router.query.id;
    if (ID) {
      const CAR_DATA = Products_json_all.filter((el: { id: number | string }) => {
        if (el.id == ID) {
          return el;
        }
      });
      setCar(CAR_DATA[0]);
    }
  }, [router.query.id]);
  
  const Form = () => {
    const [Form_data, setForm_data] = useState<any>({
      msg: "",
    })
  }

  const [msg, setMsg] = useState<any>("")

  const preventDefault = (e:any) => {
    e.preventDefault()
    console.log()
  }
  return (
    <>
      <Head>
        <title>{car?.name}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className={s.hero}>
          <form className={s.form} onSubmit={preventDefault}>
            <div className={s.form__info}>
            <label htmlFor="textarea"><span>Owner:</span> {car?.owner}</label> 
            <h2>{car?.owner} <span>socials:</span></h2>
            {
              car?.links ? <div className={s.form__info_links}>{(car?.links).map((link:string)=>{
                if(link=="Telegram"){
                  return(
                    <Link target='_blank' href="/zaglushka">
                      <Image className={s.tg} width={10} height={10} unoptimized src={Tg} alt="inst-logo"></Image>
                    </Link>
                  )
                }
                if(link=="Instagram"){
                  return(
                    <Link target='_blank' href="/zaglushka">
                      <Image className={s.fb} width={10} height={10} unoptimized src={Fb} alt="inst-logo"></Image>
                    </Link>
                  )
                }
                if(link=="Facebook"){
                  return(
                    <Link target='_blank' href="/zaglushka">
                      <Image className={s.inst} width={10} height={10} unoptimized src={Inst} alt="inst-logo"></Image>
                    </Link>
                  )
                }
              })
            }</div> : <span className={s.form__info_noLinks}>No links connected</span>}
              <Link href={`/product/${car?.id}`}>Back to Car</Link>
            </div>
            <div className={s.form__textarea}>
              <textarea maxLength={300} placeholder='Your text here..'></textarea>
              <input type="submit" value="Send" />
            </div>
          </form>
        </section>
      </main>
    </>
  )
}

// value={Form_data.msg} name="textarea" onChange={(e)=>{setFormData<any>({...Form_data, msg: e.target.value})}} 

export default cta
